/** Public project shelf used by the blurb test page. */

export const PROJECT_LANES = [
  { id: "all", label: "All" },
  { id: "product", label: "Products" },
  { id: "client", label: "Client work" },
  { id: "haiti", label: "Haiti" },
];

export const PROJECTS = [
  {
    id: "liv-lakay",
    name: "Liv Lakay",
    lane: "haiti",
    blurb: "School books Haitian kids can read on a phone.",
    href: "/liv.html",
  },
  {
    id: "mange-lakay",
    name: "Mangé Lakay",
    lane: "haiti",
    blurb: "Food, land, and a 40-year plan to build Kotfè.",
    href: "/learnViews/learn.html#kotfe",
  },
  {
    id: "tech-academy",
    name: "Tech Academy",
    lane: "product",
    blurb: "Tech training built for people 55 and up.",
    href: "/techAcademy.html",
  },
  {
    id: "fat-loss",
    name: "Fat Loss App",
    lane: "product",
    blurb: "A simple ledger for calories, protein, and daily meals.",
    href: "/fatLoss.html",
  },
  {
    id: "style-ai",
    name: "Style AI",
    lane: "product",
    blurb: "Try a new hairstyle on a selfie before you commit.",
    href: "/styleAI.html",
  },
  {
    id: "roxanne-ai",
    name: "Roxanne AI",
    lane: "product",
    blurb: "Pick a look, then see it on your face.",
    href: "/roxanneAI.html",
  },
  {
    id: "tm-experience",
    name: "TM Experience",
    lane: "product",
    blurb: "Agendas and speech tools for Toastmasters clubs.",
    href: "/TMExperience.html",
  },
  {
    id: "strangest-secret",
    name: "The Strangest Secret",
    lane: "product",
    blurb: "Earl Nightingale's 30-day goal challenge, as an app.",
    href: "/strangestSecret.html",
  },
  {
    id: "green-books",
    name: "Green Books",
    lane: "product",
    blurb: "A reading app for books you actually want to finish.",
    href: "https://green-books-app.web.app/",
  },
  {
    id: "secret-attraction-book",
    name: "A Secret Attraction",
    lane: "product",
    blurb: "A novel about mentorship, ambition, and desire.",
    href: "https://www.amazon.com/Secret-Attraction-Between-Mentor-Mentee/dp/B0DH2ZJ57H",
  },
  {
    id: "dial-crm",
    name: "Dial CRM",
    lane: "product",
    blurb: "A light CRM so follow-ups do not go cold.",
    href: "/dialer.html",
  },
  {
    id: "beach-delivery",
    name: "Beach Delivery",
    lane: "client",
    blurb: "Ordering for a beach delivery business.",
    href: "/beachDelivery.html",
  },
  {
    id: "plumbing",
    name: "Current Flow Plumbing",
    lane: "client",
    blurb: "A site that helps a plumber get found and called.",
    href: "/plumbing.html",
  },
  {
    id: "danny",
    name: "Danny's Delights",
    lane: "client",
    blurb: "A shopfront for a local food brand.",
    href: "/danny.html",
  },
  {
    id: "josh",
    name: "Joshua Williams Real Estate",
    lane: "client",
    blurb: "A landing page for a real estate practice.",
    href: "/josh.html",
  },
  {
    id: "church-network",
    name: "Church Network",
    lane: "client",
    blurb: "Tools for a church to stay connected.",
    href: "/churchNetwork.html",
  },
  {
    id: "mars",
    name: "BettrLife Financial",
    lane: "client",
    blurb: "A financial offer page for BettrLife.",
    href: "/mars.html",
  },
  {
    id: "minorities",
    name: "The Minorities",
    lane: "client",
    blurb: "A landing and community page for The Minorities.",
    href: "/minoritiesLanding.html",
  },
];
