/** Public project shelf for the Learn Projects tab. */

export const PROJECT_LANES = [
  { id: "all", label: "All" },
  { id: "product", label: "Products" },
  { id: "client", label: "Client work" },
  { id: "haiti", label: "Haiti" },
];

export const PROJECTS = [
  {
    id: "liv-lakay",
    name: "Liv Lakay",
    lane: "haiti",
    blurb: "School books Haitian kids can read on a phone.",
    href: "/liv.html",
    more: "Liv Lakay is a digital library of grade-level school books. A student can open a book on a phone or computer at home or at school. It exists because books are still hard to get for too many children in Haiti. For a client, this is a full reading product: library, access, and a mission-backed brand. For a student, it is a real shipped app with auth, content, and a reader.",
    stack: ["HTML", "CSS", "JavaScript", "Firebase Auth", "Firestore", "Stripe"],
  },
  {
    id: "mange-lakay",
    name: "Mangé Lakay",
    lane: "haiti",
    blurb: "Food, land, and a 40-year plan to build Kotfè.",
    href: "/learnViews/learn.html#kotfe",
    more: "Mangé Lakay is the live project behind this site: grow food in Kotfè, reinvest profit, and build toward a city that can feed itself. The page is a long-form pitch with donation tiers, Stripe checkout, and a Calendly path for the $100K deployment. For a client, it shows a sales page plus payments. For a student, it is HTML, config-driven tiers, and checkout links.",
    stack: ["HTML", "CSS", "JavaScript", "Stripe Payment Links", "Calendly"],
  },
  {
    id: "tech-academy",
    name: "Tech Academy",
    lane: "product",
    blurb: "Tech training built for people 55 and up.",
    href: "/techAcademy.html",
    more: "Tech Mastery For Seniors is a course and academy funnel: guides, seminars, and a VIP in-person track. The site sells the offer, explains the program, and books a call. For a client, this is a complete education funnel. For a student, it is landing pages, offer tiers, and checkout.",
    stack: ["HTML", "CSS", "JavaScript", "Stripe", "Calendly"],
  },
  {
    id: "fat-loss",
    name: "Fat Loss App",
    lane: "product",
    blurb: "A simple ledger for calories, protein, and daily meals.",
    href: "/fatLoss.html",
    more: "The Fat Loss product pairs a book-style reader with a meal ledger. Users log food, see calories and protein, and keep a daily record. Auth and cloud sync keep the ledger on more than one device. For a client, this is a consumer app with login and saved data. For a student, it is UI, state, and Firebase.",
    stack: ["HTML", "CSS", "JavaScript", "Firebase Auth", "Firestore"],
  },
  {
    id: "style-ai",
    name: "Style AI",
    lane: "product",
    blurb: "Try a new hairstyle on a selfie before you commit.",
    href: "/styleAI.html",
    more: "Style AI takes a selfie or upload, then asks Gemini to render a new hairstyle and color. The visitor pastes their own Gemini key in the browser. For a client, this is an AI try-on product. For a student, it is a front end that calls an image model from the browser.",
    stack: ["HTML", "CSS", "JavaScript", "Gemini image API"],
  },
  {
    id: "roxanne-ai",
    name: "Roxanne AI",
    lane: "product",
    blurb: "Pick a look, then see it on your face.",
    href: "/roxanneAI.html",
    more: "Roxanne AI is a hairstyle try-on that fits SVG hair over a face. It uses the camera or an upload, then lets you drag, size, and tint the style. For a client, this is a visual tool with no server. For a student, it is canvas-style overlay work plus face landmarks.",
    stack: ["HTML", "CSS", "JavaScript", "SVG", "MediaPipe"],
  },
  {
    id: "tm-experience",
    name: "TM Experience",
    lane: "product",
    blurb: "Agendas and speech tools for Toastmasters clubs.",
    href: "/TMExperience.html",
    more: "TM Experience helps a Toastmasters club run meetings: agendas, speech tracking, and tools members can use between sessions. Clubs sign in with a club ID. For a client, this is a members area for a real organization. For a student, it is multi-view app structure and Firebase-backed club data.",
    stack: ["HTML", "CSS", "JavaScript", "Firebase Auth", "Firestore"],
  },
  {
    id: "strangest-secret",
    name: "The Strangest Secret",
    lane: "product",
    blurb: "Earl Nightingale's 30-day goal challenge, as an app.",
    href: "/strangestSecret.html",
    more: "A companion for Earl Nightingale's 30-day test: write a goal, listen daily, and track the habit. It runs in the browser with no account. For a client, this is a focused habit product. For a student, it is local state, audio, and a small UI system.",
    stack: ["HTML", "CSS", "JavaScript", "localStorage"],
  },
  {
    id: "green-books",
    name: "Green Books",
    lane: "product",
    blurb: "A reading app for books you actually want to finish.",
    href: "https://green-books-app.web.app/",
    more: "Green Books is a hosted reader: open a book, move through pages, and keep your place. It lives on Firebase Hosting as its own app. For a client, this is a content product with a dedicated host. For a student, it is a reader UI shipped as a static web app.",
    stack: ["HTML", "CSS", "JavaScript", "Firebase Hosting"],
  },
  {
    id: "secret-attraction-book",
    name: "A Secret Attraction",
    lane: "product",
    blurb: "A novel about mentorship, ambition, and desire.",
    href: "https://www.amazon.com/Secret-Attraction-Between-Mentor-Mentee/dp/B0DH2ZJ57H",
    more: "A published novel on Amazon, with a site that presents the book and the story. For a client, this is proof of shipping a long creative project plus a sales page. For a student, the site is a straightforward marketing front end.",
    stack: ["HTML", "CSS", "JavaScript", "Amazon KDP"],
  },
  {
    id: "dial-crm",
    name: "Dial CRM",
    lane: "product",
    blurb: "A light CRM so follow-ups do not go cold.",
    href: "/dialer.html",
    more: "Dial CRM is a contact and follow-up board for people who sell. Import a sheet, keep notes, and see who needs a call. It runs in the browser. For a client, this is a working internal tool. For a student, it is tables, local workflow, and spreadsheet import.",
    stack: ["HTML", "CSS", "JavaScript", "SheetJS"],
  },
  {
    id: "beach-delivery",
    name: "Beach Delivery",
    lane: "client",
    blurb: "Ordering for a beach delivery business.",
    href: "/beachDelivery.html",
    more: "A client site for a beach delivery service: show what you sell and make it easy to order. For a client, this is a local-business site with a real use case. For a student, it is a focused HTML and CSS build with an order flow.",
    stack: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "plumbing",
    name: "Current Flow Plumbing",
    lane: "client",
    blurb: "A site that helps a plumber get found and called.",
    href: "/plumbing.html",
    more: "A service-business page: who they are, what they do, and how to call. This is the $997-style job in the wild. For a client, this is what a starter site looks like. For a student, it is a one-page marketing build.",
    stack: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "danny",
    name: "Danny's Delights",
    lane: "client",
    blurb: "A shopfront for a local food brand.",
    href: "/danny.html",
    more: "A brand page for a local food business: offer, photos, and a reason to order. For a client, this is a simple shopfront. For a student, it is layout, copy, and a clear call to action.",
    stack: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "josh",
    name: "Joshua Williams Real Estate",
    lane: "client",
    blurb: "A landing page for a real estate practice.",
    href: "/josh.html",
    more: "A personal brand page for an agent: trust, contact, and the next step. For a client, this is a professional one-pager. For a student, it is a clean landing-page structure.",
    stack: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "church-network",
    name: "Church Network",
    lane: "client",
    blurb: "Tools for a church to stay connected.",
    href: "/churchNetwork.html",
    more: "A church-facing site for staying in touch with members and visitors. For a client, this is community software in a small package. For a student, it is a multi-page HTML app with a clear audience.",
    stack: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "mars",
    name: "BettrLife Financial",
    lane: "client",
    blurb: "A financial offer page for BettrLife.",
    href: "/mars.html",
    more: "A sales landing page for a financial offer: headline, proof, and a sticky call to action. For a client, this is a conversion page. For a student, it is landing-page rhythm and CTA placement.",
    stack: ["HTML", "CSS", "JavaScript"],
  },
  {
    id: "minorities",
    name: "The Minorities",
    lane: "client",
    blurb: "A landing and community page for The Minorities.",
    href: "/minoritiesLanding.html",
    more: "A public site for The Minorities: posts, cards, and a place to join the story. For a client, this is a community brand on the web. For a student, it is a content-driven front end.",
    stack: ["HTML", "CSS", "JavaScript"],
  },
];
