window.PRINCES_CATALOG = {
  brand: "Princes",
  tagline: "To all aspiring princes",
  workingLogo: "princesView/assets/logos/princes-logo-crown.png",
  names: [
    { id: "princes", name: "Princes", note: "Working name. Direct. The man and the aim in one word." },
    { id: "the-court", name: "The Court", note: "The room they want to enter. Leaves Prince's Court for the top tier." },
    { id: "first-kingdom", name: "First Kingdom", note: "Matches the body-is-the-kingdom line." },
    { id: "court-of-ten", name: "Court of Ten", note: "10% body fat as the first law." },
    { id: "the-principate", name: "The Principate", note: "Older, heavier. Sounds like a government of princes." },
    { id: "crown-law", name: "Crown Law", note: "Rules first. Body first." },
    { id: "aspiring-princes", name: "Aspiring Princes", note: "Says who it is for. Softer than Princes." },
    { id: "ten-percent-court", name: "Ten Percent Court", note: "Literal. Easy to remember. Long on a logo." },
  ],
  headlines: [
    "Your body is your first kingdom",
    "Build the king before the kingdom",
    "A weak body cannot hold a throne",
    "10% body fat is the first law",
    "Fix the man in the mirror first",
  ],
  tiers: [
    {
      id: "ticket",
      name: "Squire",
      price: 1,
      cadence: "once",
      label: "$1 ticket",
      perks: "The fat-loss course. The upgrade letter. No community yet.",
      access: ["course:body"],
    },
    {
      id: "household",
      name: "The Household",
      price: 14.97,
      cadence: "month",
      label: "$14.97 / month",
      perks: "All current courses. Live classes. Posts. Member chat.",
      access: ["course:body", "learn", "posts", "chat", "calendar"],
    },
    {
      id: "court",
      name: "Prince's Court",
      price: 1000000,
      cadence: "year",
      label: "$1,000,000 / year",
      perks: "Private mastermind. Princes talking to princes. Knowledge exchange only.",
      access: ["course:body", "learn", "posts", "chat", "calendar", "mastermind"],
    },
  ],
  midOffers: [
    {
      id: "knight",
      name: "Knight",
      price: 47,
      cadence: "month",
      idea: "Weekly group call. Homework. A sergeant in the room.",
    },
    {
      id: "baron",
      name: "Baron",
      price: 197,
      cadence: "month",
      idea: "A pod of 8 men. Weekly scoreboard. Someone notices if you slip.",
    },
    {
      id: "lord",
      name: "Lord",
      price: 497,
      cadence: "month",
      idea: "Monthly 1:1. Plan written with you. Every course unlocked.",
    },
    {
      id: "duke",
      name: "Duke",
      price: 4997,
      cadence: "year",
      idea: "One retreat. A private channel. Introductions inside the court.",
    },
    {
      id: "crown",
      name: "Crown Seat",
      price: 25000,
      cadence: "year",
      idea: "Operator seat. You help run a project. You sit closer to the princes.",
    },
  ],
  topics: {
    body: { label: "Body", color: "#C9A227" },
    mindset: { label: "Mindset", color: "#6B4C9A" },
    app: { label: "App", color: "#1F6FEB" },
    business: { label: "Business", color: "#0F7B4A" },
    city: { label: "City", color: "#B42318" },
  },
  teamRoles: ["member", "leader", "staff", "owner"],
  courses: [
    {
      id: "body",
      title: "How to lose fat as fast as humanly possible",
      meta: "Your first kingdom",
      topic: "body",
      access: "ticket",
      image: "princesView/assets/courses/body.png",
      href: "#course/body",
    },
  ],
  classes: [
    {
      id: "class-body-1",
      title: "10% body fat: the first law",
      when: "Tue Oct 7 · 8:00 PM ET",
      topic: "body",
      sub: "Why every man in this court starts with the mirror.",
    },
    {
      id: "class-mind-1",
      title: "The prince's morning",
      when: "Thu Oct 9 · 7:00 AM ET",
      topic: "mindset",
      sub: "A short rule set for the first hour of the day.",
    },
    {
      id: "class-biz-1",
      title: "Price like a prince",
      when: "Sat Oct 11 · 11:00 AM ET",
      topic: "business",
      sub: "How men who sell well stop apologizing for the number.",
    },
  ],
  events: [
    { id: "e1", title: "10% body fat: the first law", date: "2026-10-07", time: "20:00", topic: "body", sub: "Live class. Bring your current weight and waist." },
    { id: "e2", title: "The prince's morning", date: "2026-10-09", time: "07:00", topic: "mindset", sub: "Live class. First-hour rules." },
    { id: "e3", title: "Price like a prince", date: "2026-10-11", time: "11:00", topic: "business", sub: "Live class. Offer, price, close." },
    { id: "e4", title: "Build a simple app this month", date: "2026-10-14", time: "19:00", topic: "app", sub: "Workshop. Ship one page that takes money." },
    { id: "e5", title: "City night: Kotfè", date: "2026-10-18", time: "18:00", topic: "city", sub: "How a town gets food, streets, and owners." },
    { id: "e6", title: "Waist check", date: "2026-10-21", time: "20:00", topic: "body", sub: "Accountability. Post the number." },
    { id: "e7", title: "Mindset office hours", date: "2026-10-21", time: "12:00", topic: "mindset", sub: "Open questions. 45 minutes." },
    { id: "e8", title: "Offer review", date: "2026-10-21", time: "16:00", topic: "business", sub: "Bring one offer. We tighten it live." },
    { id: "e9", title: "App office hours", date: "2026-10-21", time: "21:00", topic: "app", sub: "Unstick your build." },
  ],
  seedPosts: [
    {
      id: "p1",
      author: "Képler",
      role: "owner",
      title: "Your body is your first kingdom",
      body: "If you do not like the man in the mirror, change him first. A weak king trains a weak court. Get to 10% body fat.",
      topic: "body",
    },
    {
      id: "p2",
      author: "Staff",
      role: "staff",
      title: "Household is open",
      body: "Squires who finish the fat course can step into The Household. Classes, posts, and chat start there.",
      topic: "mindset",
    },
  ],
};
